### ISSUE TITLE
DLL file is Missing

### ISSUE THREAD

**Issue by TithiPatel57** [NetSim-TETCOS/FOG_COMPUTING_v10.2#1]
Not able to find DLL file from this git folder 
If anyone is having it Please share it here.

**Comment by NetSim-TETCOS** [comment]
Hello Tithi,

This project belongs to NetSim v10.2. You can open the source codes in Visual studio using the NetSim.sln visual studio solution file and build to obtain the DLL files. 
Please note that you will need NetSim to be able to use the output DLL files. If you are an existing user of NetSim, you may write to support@tetcos.com for technical support.

Regards,
Team NetSim
